// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8eB83k_hjlfnrepDD5AQwZsC3wtImRGM',
    appId: '1:109191738726:web:f8eb82997b1762c6ab04a7',
    messagingSenderId: '109191738726',
    projectId: 'shipment-tracking-ec5db',
    authDomain: 'shipment-tracking-ec5db.firebaseapp.com',
    storageBucket: 'shipment-tracking-ec5db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu7qd-TFwC6q7TeoAAyndRTkcjq2gqykI',
    appId: '1:109191738726:android:25bfc5d7650075efab04a7',
    messagingSenderId: '109191738726',
    projectId: 'shipment-tracking-ec5db',
    storageBucket: 'shipment-tracking-ec5db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWoXwVW5ZYOGdLx0rW2vePcZQATtbCpJ0',
    appId: '1:109191738726:ios:273ab278b0e34f3fab04a7',
    messagingSenderId: '109191738726',
    projectId: 'shipment-tracking-ec5db',
    storageBucket: 'shipment-tracking-ec5db.appspot.com',
    iosBundleId: 'com.example.shipmentTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWoXwVW5ZYOGdLx0rW2vePcZQATtbCpJ0',
    appId: '1:109191738726:ios:273ab278b0e34f3fab04a7',
    messagingSenderId: '109191738726',
    projectId: 'shipment-tracking-ec5db',
    storageBucket: 'shipment-tracking-ec5db.appspot.com',
    iosBundleId: 'com.example.shipmentTracking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8eB83k_hjlfnrepDD5AQwZsC3wtImRGM',
    appId: '1:109191738726:web:3cc7337cb7213f52ab04a7',
    messagingSenderId: '109191738726',
    projectId: 'shipment-tracking-ec5db',
    authDomain: 'shipment-tracking-ec5db.firebaseapp.com',
    storageBucket: 'shipment-tracking-ec5db.appspot.com',
  );
}
